name: classified_flutter
description: A new Flutter project.
version: 1.0.2+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bot_toast: ^2.2.1
  cloud_firestore: ^0.13.0+1
  cupertino_icons: ^0.1.3
  firebase_auth: 0.16.0
  firebase_core: ^0.4.4+3
  firebase_messaging: ^5.1.8
  firebase_storage: ^3.0.8
  connectivity: ^0.4.5+3
  url_launcher: ^5.2.5
  google_sign_in: ^4.0.14
  provider: ^4.0.5+1
  get_it: ^4.0.2
  path_provider: ^1.6.5
  flutter_icons: ^1.0.0+1
  badges: ^1.1.0
  image_picker: ^0.6.3+1
  multi_image_picker: ^4.6.5+rc.1
  cached_network_image: ^2.0.0-rc
  flutter_cache_manager: ^1.1.3
  flutter_image_compress: ^0.6.3
  animated_text_kit: ^1.3.0
  flutter_masked_text: ^0.7.0
  font_awesome_flutter: ^8.5.0
  google_fonts: ^0.3.7
  loading_animations: ^2.1.0
  intl: ^0.15.7
  circular_check_box: ^0.0.2
  uuid: ^2.0.0
  recase: ^2.0.1
  csv: ^4.0.1
  flutter_mailer: ^0.4.0+1
  awesome_loader: ^0.0.3
  flutter_easyrefresh: ^1.2.7
  package_info: ^0.4.0+16
  hive: ^1.4.1+1
  http: ^0.12.0+4
  dio: ^3.0.9
  flutter_launcher_icons: ^0.7.4
  carousel_slider: ^2.1.0


flutter_icons:
  image_path: "assets/icon/icon.jpg"
  android: true
  ios: true
 
dev_dependencies:
  flutter_test:
      sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - google_fonts/
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: google_fonts/Lato-Thin.ttf
          weight: 100
        - asset: google_fonts/Lato-ThinItalic.ttf
          style: italic
        - asset: google_fonts/Lato-Light.ttf
          weight: 300
        - asset: google_fonts/Lato-LightItalic.ttf
          style: italic
        - asset: google_fonts/Lato-Regular.ttf
          weight: 500
        - asset: google_fonts/Lato-Italic.ttf
          style: italic
        - asset: google_fonts/Lato-Bold.ttf
          weight: 700
        - asset: google_fonts/Lato-BoldItalic.ttf
          style: italic
        - asset: google_fonts/Lato-Black.ttf
          weight: 900
        - asset: google_fonts/Lato-BlackItalic.ttf
          style: italic
